name: Run test suite
on: push

jobs:
  run-tests:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    container:
      image: alpine
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Running alpine install
        run: npm install
      - name: Running phpunit
        run: ./vendor/bin/phpunit tests
